#!/bin/bash

if test $# -ne 2
        then
			echo "Display user job history"
			echo "Default to display job history for last 7 days for current user"
			echo "Usage: userjobhist days user"
fi			

set -e -o pipefail

if [[ -z $1 ]]; then
    days=7
else
    days=$1
    if [[ $1 =~ [[:alpha:]] || $1 -lt 1 ]]; then
        printf "%s\n" "Error: The first argument should be a positive integer indicating days to list in history"
        exit 1
    fi
fi

if [[ -z $2 ]]; then
    user=$USER
else
    user=$2
    # Check if user exists
    if [[ "$(id $user 2>&1)" = *"no such user"* ]]; then
        printf "%s\n" "No such user: $user"
        exit 1
    fi
fi

# Set sacct format
format=user%9,start%10,jobid%13,jobname%12,partition,state,elapsed%11,nnodes%5,ncpus%4,reqmem%8,reqtres%-50

printf "%s\n" "----------------------------------------------------------------------------------------------------------"
printf "%s\n" "   User   Startdate        Job ID     Job Name  Partition      State     Elapsed Nodes CPUs   Memory GPUs"
printf "%s\n" "--------- ---------- ------------- ------------ ---------- ---------- ----------- ----- ---- -------- ----"
sacct -n -X -o $format -u $user -S $(date --date="-$days day" +%Y-%m-%d) |
    # Extract number of GPUs requested
    sed -r 's/billing=.*gres\/gpu=([^,]*),.*/\1/; s/billing=.*/0/'
